#!/bin/bash -l

################################################################################
#Script Name: sal_out_collect.pbs
#Desription : collect salmon output into matrices
#Args       : dir, genome, outfile suffix
#Author     : Georgia Doing
#Date       : 12-18-20
#Email      : Georgia.Doing.GR@Dartmouth.edu
################################################################################

#SBATCH --job-name spu_out_col
#SBATCH --time=02:00:00
#$BATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mail-type=BEGIN,END,FAIL



cd ~/salmon

Rscript quant_collect.R /dartfs-hpc/rc/lab/H/HoganD/RNASeq_data/Sputum_Metals_RNAseq/salmon_out \
pao1_asm676v1cdna_gene_names.csv \
spu_metals_pao1_cdna_k15.csv
#wait
#cp *spu_metals_pao1_cdna_k15.csv /dartfs-hpc/rc/lab/H/HoganD/RNASeq_data/Sputum_Metals_RNAseq
